version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: expenses-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses
      MYSQL_USER: expenses_user
      MYSQL_PASSWORD: expenses_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

